# path to phantomjs directory - example: '/home/user/phantomjs-1.9.7-linux-x86_64/bin/'
PHANTOMJS_DIRECTORY = '/home/user/phantomjsdirectory/'
# full path to wparser directory, which is actually current working directory - example: '/home/user/wparserjspath/dev/wparser'
WPARSER_DIRECTORY = '/home/user/wparserdirectory'
# full path to CSS file - example: '/home/user/dev/wparser/input/test.csv'
CSV_PATH = '/home/user/wparserdirectory/input/test.csv'